define anon = Character("未知")
define me = Character("userName")
define ai = Character("小爱")
define sister = Character("game.character.female.sister.username")
define cousin = Character("game.character.female.cousin.username")