/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@renderer/layouts/base-layout/index.vue";
import BlankLayout from "@renderer/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  archive: () => import("@renderer/views/_constants/archive/index.vue"),
  demo: () => import("@renderer/views/_constants/demo/index.vue"),
  gallery: () => import("@renderer/views/_constants/gallery/index.vue"),
  personal: () => import("@renderer/views/_constants/personal/index.vue"),
  setting: () => import("@renderer/views/_constants/setting/index.vue"),
  403: () => import("@renderer/views/_error/403/index.vue"),
  404: () => import("@renderer/views/_error/404/index.vue"),
  500: () => import("@renderer/views/_error/500/index.vue"),
  achievement: () => import("@renderer/views/achievement/index.vue"),
  backpack: () => import("@renderer/views/backpack/index.vue"),
  character: () => import("@renderer/views/character/index.vue"),
  home: () => import("@renderer/views/home/index.vue"),
  login: () => import("@renderer/views/login/index.vue"),
  relationship: () => import("@renderer/views/relationship/index.vue"),
  task: () => import("@renderer/views/task/index.vue"),
};
